### ISSUE TITLE
JavaScript error in dashboard after providing all input fields

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-stale-playlist-detector#17]
dashboard.js:130 MissingRequiredParameter: Missing required key 'TableName' in params
    at constructor.fail (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:62:29767)
    at constructor.validateStructure (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:62:29977)
    at constructor.validateMember (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:62:30353)
    at constructor.validate (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:62:29423)
    at constructor.<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:62:4316)
    at constructor.callListeners (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:64:5128)
    at s (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:64:4994)
    at https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:62:3649
    at t (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:61:4075)
    at https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:61:4396 "MissingRequiredParameter: Missing required key 'TableName' in params
    at constructor.fail (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:62:29767)
    at constructor.validateStructure (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:62:29977)
    at constructor.validateMember (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:62:30353)
    at constructor.validate (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:62:29423)
    at constructor.<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:62:4316)
    at constructor.callListeners (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:64:5128)
    at s (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:64:4994)
    at https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:62:3649
    at t (https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:61:4075)
    at https://sdk.amazonaws.com/js/aws-sdk-2.480.0.min.js:61:4396"

**Comment by JimTharioAmazon** [comment]
Updated and simplified some of dashboard.js. Added push button start/stop in polling and an alert at the top for exceptions while running.
